export const COMPLIMENT = 'compliment';

export const COMPLIMENT_MOUNT = 'COMPLIMENT_MOUNT';
export const CONFIRM_COMPLIMENT = 'CONFIRM_COMPLIMENT';
export const CANCEL_COMPLIMENT = 'CANCEL_COMPLIMENT';